package dao;

import pojo.Aftersale;

public interface AftersaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_aftersale
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_aftersale
     *
     * @mbggenerated
     */
    int insert(Aftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_aftersale
     *
     * @mbggenerated
     */
    int insertSelective(Aftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_aftersale
     *
     * @mbggenerated
     */
    Aftersale selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_aftersale
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Aftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_aftersale
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Aftersale record);
}