package dao;

import pojo.CouponUser;

public interface CouponUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_coupon_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_coupon_user
     *
     * @mbggenerated
     */
    int insert(CouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_coupon_user
     *
     * @mbggenerated
     */
    int insertSelective(CouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_coupon_user
     *
     * @mbggenerated
     */
    CouponUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_coupon_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_coupon_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CouponUser record);
}