package dao;

import org.apache.ibatis.annotations.Param;
import pojo.Coupon;

import java.util.List;

public interface CouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_coupon
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_coupon
     *
     * @mbggenerated
     */
    int insert(Coupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_coupon
     *
     * @mbggenerated
     */
    int insertSelective(Coupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_coupon
     *
     * @mbggenerated
     */
    Coupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_coupon
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Coupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_coupon
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Coupon record);

    List<Coupon> getAllCoupons(@Param("page") Integer page, @Param("limit") Integer limit);

    void selectByPrimaryKey();
}