package dao;

import pojo.Footprint;

public interface FootprintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_footprint
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_footprint
     *
     * @mbggenerated
     */
    int insert(Footprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_footprint
     *
     * @mbggenerated
     */
    int insertSelective(Footprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_footprint
     *
     * @mbggenerated
     */
    Footprint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_footprint
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Footprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_footprint
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Footprint record);
}