package dao;

import org.apache.ibatis.annotations.Param;
import pojo.Goods;

import java.util.List;

public interface GoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_goods
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_goods
     *
     * @mbggenerated
     */
    int insert(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_goods
     *
     * @mbggenerated
     */
    int insertSelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_goods
     *
     * @mbggenerated
     */
    Goods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Goods record);

    List<Goods> getGoodsList(@Param("isNew") Boolean isNew, @Param("isHot") Boolean isHot,
                             @Param("keyword") String keyword, @Param("brandId") Integer brandId,
                             @Param("categoryId") Integer categoryId, @Param("page") Integer page,
                             @Param("limit") Integer limit, @Param("sort") String sort,
                             @Param("order") String order);


    List<Goods> getGoodsListAdmin(@Param("goodsId") Integer goodsId, @Param("goodsSn") String goodsSn,
                             @Param("name") String name, @Param("page") Integer page,
                             @Param("limit") Integer limit, @Param("sort") String sort,
                             @Param("order") String order);

    List<Goods> getLatestGoods(@Param("page") Integer page, @Param("limit") Integer limit);

    List<Goods> getHotGoods(@Param("page") Integer page, @Param("limit") Integer limit);

    List<Goods> getFloorGoods();

    int getGoodsCount();
}