package dao;

import pojo.GoodsProduct;

import java.util.List;

public interface GoodsProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_goods_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_goods_product
     *
     * @mbggenerated
     */
    int insert(GoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_goods_product
     *
     * @mbggenerated
     */
    int insertSelective(GoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_goods_product
     *
     * @mbggenerated
     */
    GoodsProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_goods_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_goods_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GoodsProduct record);

    List<GoodsProduct> selectByGoodsId(Integer id);
}