package dao;

import pojo.GoodsSpecification;

public interface GoodsSpecificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_goods_specification
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_goods_specification
     *
     * @mbggenerated
     */
    int insert(GoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_goods_specification
     *
     * @mbggenerated
     */
    int insertSelective(GoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_goods_specification
     *
     * @mbggenerated
     */
    GoodsSpecification selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_goods_specification
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_goods_specification
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GoodsSpecification record);
}