package dao;

import pojo.GoodsAttribute;

public interface GoodsAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_goods_attribute
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_goods_attribute
     *
     * @mbggenerated
     */
    int insert(GoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_goods_attribute
     *
     * @mbggenerated
     */
    int insertSelective(GoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_goods_attribute
     *
     * @mbggenerated
     */
    GoodsAttribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_goods_attribute
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_goods_attribute
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GoodsAttribute record);
}