package dao;

import pojo.Groupon;

public interface GrouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_groupon
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_groupon
     *
     * @mbggenerated
     */
    int insert(Groupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_groupon
     *
     * @mbggenerated
     */
    int insertSelective(Groupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_groupon
     *
     * @mbggenerated
     */
    Groupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_groupon
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Groupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_groupon
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Groupon record);
}