package dao;

import org.apache.ibatis.annotations.Param;
import pojo.Groupon;

import java.util.List;

public interface GrouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_groupon
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_groupon
     *
     * @mbggenerated
     */
    int insert(Groupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_groupon
     *
     * @mbggenerated
     */
    int insertSelective(Groupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_groupon
     *
     * @mbggenerated
     */
    Groupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_groupon
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Groupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_groupon
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Groupon record);

    Groupon selectByOrderId(Integer id);

    List<Groupon> getAllGroupons(@Param("page") Integer page, @Param("limit") Integer limit);
}