package dao;

import pojo.Issue;

public interface IssueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_issue
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_issue
     *
     * @mbggenerated
     */
    int insert(Issue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_issue
     *
     * @mbggenerated
     */
    int insertSelective(Issue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_issue
     *
     * @mbggenerated
     */
    Issue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_issue
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Issue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_issue
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Issue record);
}