package dao;

import pojo.Keyword;

public interface KeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_keyword
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_keyword
     *
     * @mbggenerated
     */
    int insert(Keyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_keyword
     *
     * @mbggenerated
     */
    int insertSelective(Keyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_keyword
     *
     * @mbggenerated
     */
    Keyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_keyword
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Keyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_keyword
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Keyword record);
}