package dao;

import pojo.NoticeAdmin;

public interface NoticeAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_notice_admin
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_notice_admin
     *
     * @mbggenerated
     */
    int insert(NoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_notice_admin
     *
     * @mbggenerated
     */
    int insertSelective(NoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_notice_admin
     *
     * @mbggenerated
     */
    NoticeAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_notice_admin
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_notice_admin
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NoticeAdmin record);
}