package dao;

import pojo.SearchHistory;

public interface SearchHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_search_history
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_search_history
     *
     * @mbggenerated
     */
    int insert(SearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_search_history
     *
     * @mbggenerated
     */
    int insertSelective(SearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_search_history
     *
     * @mbggenerated
     */
    SearchHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_search_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_search_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SearchHistory record);
}