package dao;

import org.apache.ibatis.annotations.Param;
import pojo.Topic;

import java.util.List;

public interface TopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_topic
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_topic
     *
     * @mbggenerated
     */
    int insert(Topic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_topic
     *
     * @mbggenerated
     */
    int insertSelective(Topic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_topic
     *
     * @mbggenerated
     */
    Topic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_topic
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Topic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_topic
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Topic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table librecmall_topic
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Topic record);

    List<Topic> getAllTopics(@Param("page") Integer page, @Param("limit") Integer limit);
}