package pojo;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_comment.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_comment.value_id
     *
     * @mbggenerated
     */
    private Integer valueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_comment.type
     *
     * @mbggenerated
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_comment.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_comment.admin_content
     *
     * @mbggenerated
     */
    private String adminContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_comment.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_comment.has_picture
     *
     * @mbggenerated
     */
    private Boolean hasPicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_comment.pic_urls
     *
     * @mbggenerated
     */
    private String picUrls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_comment.star
     *
     * @mbggenerated
     */
    private Short star;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_comment.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_comment.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_comment.deleted
     *
     * @mbggenerated
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_comment.id
     *
     * @return the value of librecmall_comment.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_comment.id
     *
     * @param id the value for librecmall_comment.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_comment.value_id
     *
     * @return the value of librecmall_comment.value_id
     *
     * @mbggenerated
     */
    public Integer getValueId() {
        return valueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_comment.value_id
     *
     * @param valueId the value for librecmall_comment.value_id
     *
     * @mbggenerated
     */
    public void setValueId(Integer valueId) {
        this.valueId = valueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_comment.type
     *
     * @return the value of librecmall_comment.type
     *
     * @mbggenerated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_comment.type
     *
     * @param type the value for librecmall_comment.type
     *
     * @mbggenerated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_comment.content
     *
     * @return the value of librecmall_comment.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_comment.content
     *
     * @param content the value for librecmall_comment.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_comment.admin_content
     *
     * @return the value of librecmall_comment.admin_content
     *
     * @mbggenerated
     */
    public String getAdminContent() {
        return adminContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_comment.admin_content
     *
     * @param adminContent the value for librecmall_comment.admin_content
     *
     * @mbggenerated
     */
    public void setAdminContent(String adminContent) {
        this.adminContent = adminContent == null ? null : adminContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_comment.user_id
     *
     * @return the value of librecmall_comment.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_comment.user_id
     *
     * @param userId the value for librecmall_comment.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_comment.has_picture
     *
     * @return the value of librecmall_comment.has_picture
     *
     * @mbggenerated
     */
    public Boolean getHasPicture() {
        return hasPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_comment.has_picture
     *
     * @param hasPicture the value for librecmall_comment.has_picture
     *
     * @mbggenerated
     */
    public void setHasPicture(Boolean hasPicture) {
        this.hasPicture = hasPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_comment.pic_urls
     *
     * @return the value of librecmall_comment.pic_urls
     *
     * @mbggenerated
     */
    public String getPicUrls() {
        return picUrls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_comment.pic_urls
     *
     * @param picUrls the value for librecmall_comment.pic_urls
     *
     * @mbggenerated
     */
    public void setPicUrls(String picUrls) {
        this.picUrls = picUrls == null ? null : picUrls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_comment.star
     *
     * @return the value of librecmall_comment.star
     *
     * @mbggenerated
     */
    public Short getStar() {
        return star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_comment.star
     *
     * @param star the value for librecmall_comment.star
     *
     * @mbggenerated
     */
    public void setStar(Short star) {
        this.star = star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_comment.add_time
     *
     * @return the value of librecmall_comment.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_comment.add_time
     *
     * @param addTime the value for librecmall_comment.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_comment.update_time
     *
     * @return the value of librecmall_comment.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_comment.update_time
     *
     * @param updateTime the value for librecmall_comment.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_comment.deleted
     *
     * @return the value of librecmall_comment.deleted
     *
     * @mbggenerated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_comment.deleted
     *
     * @param deleted the value for librecmall_comment.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}