package pojo;

import java.util.Date;

public class CouponUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_coupon_user.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_coupon_user.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_coupon_user.coupon_id
     *
     * @mbggenerated
     */
    private Integer couponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_coupon_user.status
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_coupon_user.used_time
     *
     * @mbggenerated
     */
    private Date usedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_coupon_user.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_coupon_user.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_coupon_user.order_id
     *
     * @mbggenerated
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_coupon_user.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_coupon_user.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_coupon_user.deleted
     *
     * @mbggenerated
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_coupon_user.id
     *
     * @return the value of librecmall_coupon_user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_coupon_user.id
     *
     * @param id the value for librecmall_coupon_user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_coupon_user.user_id
     *
     * @return the value of librecmall_coupon_user.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_coupon_user.user_id
     *
     * @param userId the value for librecmall_coupon_user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_coupon_user.coupon_id
     *
     * @return the value of librecmall_coupon_user.coupon_id
     *
     * @mbggenerated
     */
    public Integer getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_coupon_user.coupon_id
     *
     * @param couponId the value for librecmall_coupon_user.coupon_id
     *
     * @mbggenerated
     */
    public void setCouponId(Integer couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_coupon_user.status
     *
     * @return the value of librecmall_coupon_user.status
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_coupon_user.status
     *
     * @param status the value for librecmall_coupon_user.status
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_coupon_user.used_time
     *
     * @return the value of librecmall_coupon_user.used_time
     *
     * @mbggenerated
     */
    public Date getUsedTime() {
        return usedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_coupon_user.used_time
     *
     * @param usedTime the value for librecmall_coupon_user.used_time
     *
     * @mbggenerated
     */
    public void setUsedTime(Date usedTime) {
        this.usedTime = usedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_coupon_user.start_time
     *
     * @return the value of librecmall_coupon_user.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_coupon_user.start_time
     *
     * @param startTime the value for librecmall_coupon_user.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_coupon_user.end_time
     *
     * @return the value of librecmall_coupon_user.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_coupon_user.end_time
     *
     * @param endTime the value for librecmall_coupon_user.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_coupon_user.order_id
     *
     * @return the value of librecmall_coupon_user.order_id
     *
     * @mbggenerated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_coupon_user.order_id
     *
     * @param orderId the value for librecmall_coupon_user.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_coupon_user.add_time
     *
     * @return the value of librecmall_coupon_user.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_coupon_user.add_time
     *
     * @param addTime the value for librecmall_coupon_user.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_coupon_user.update_time
     *
     * @return the value of librecmall_coupon_user.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_coupon_user.update_time
     *
     * @param updateTime the value for librecmall_coupon_user.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_coupon_user.deleted
     *
     * @return the value of librecmall_coupon_user.deleted
     *
     * @mbggenerated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_coupon_user.deleted
     *
     * @param deleted the value for librecmall_coupon_user.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}