package pojo;

import java.util.Date;

public class Groupon {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_groupon.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_groupon.order_id
     *
     * @mbggenerated
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_groupon.groupon_id
     *
     * @mbggenerated
     */
    private Integer grouponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_groupon.rules_id
     *
     * @mbggenerated
     */
    private Integer rulesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_groupon.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_groupon.share_url
     *
     * @mbggenerated
     */
    private String shareUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_groupon.creator_user_id
     *
     * @mbggenerated
     */
    private Integer creatorUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_groupon.creator_user_time
     *
     * @mbggenerated
     */
    private Date creatorUserTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_groupon.status
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_groupon.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_groupon.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_groupon.deleted
     *
     * @mbggenerated
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_groupon.id
     *
     * @return the value of librecmall_groupon.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_groupon.id
     *
     * @param id the value for librecmall_groupon.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_groupon.order_id
     *
     * @return the value of librecmall_groupon.order_id
     *
     * @mbggenerated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_groupon.order_id
     *
     * @param orderId the value for librecmall_groupon.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_groupon.groupon_id
     *
     * @return the value of librecmall_groupon.groupon_id
     *
     * @mbggenerated
     */
    public Integer getGrouponId() {
        return grouponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_groupon.groupon_id
     *
     * @param grouponId the value for librecmall_groupon.groupon_id
     *
     * @mbggenerated
     */
    public void setGrouponId(Integer grouponId) {
        this.grouponId = grouponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_groupon.rules_id
     *
     * @return the value of librecmall_groupon.rules_id
     *
     * @mbggenerated
     */
    public Integer getRulesId() {
        return rulesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_groupon.rules_id
     *
     * @param rulesId the value for librecmall_groupon.rules_id
     *
     * @mbggenerated
     */
    public void setRulesId(Integer rulesId) {
        this.rulesId = rulesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_groupon.user_id
     *
     * @return the value of librecmall_groupon.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_groupon.user_id
     *
     * @param userId the value for librecmall_groupon.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_groupon.share_url
     *
     * @return the value of librecmall_groupon.share_url
     *
     * @mbggenerated
     */
    public String getShareUrl() {
        return shareUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_groupon.share_url
     *
     * @param shareUrl the value for librecmall_groupon.share_url
     *
     * @mbggenerated
     */
    public void setShareUrl(String shareUrl) {
        this.shareUrl = shareUrl == null ? null : shareUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_groupon.creator_user_id
     *
     * @return the value of librecmall_groupon.creator_user_id
     *
     * @mbggenerated
     */
    public Integer getCreatorUserId() {
        return creatorUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_groupon.creator_user_id
     *
     * @param creatorUserId the value for librecmall_groupon.creator_user_id
     *
     * @mbggenerated
     */
    public void setCreatorUserId(Integer creatorUserId) {
        this.creatorUserId = creatorUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_groupon.creator_user_time
     *
     * @return the value of librecmall_groupon.creator_user_time
     *
     * @mbggenerated
     */
    public Date getCreatorUserTime() {
        return creatorUserTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_groupon.creator_user_time
     *
     * @param creatorUserTime the value for librecmall_groupon.creator_user_time
     *
     * @mbggenerated
     */
    public void setCreatorUserTime(Date creatorUserTime) {
        this.creatorUserTime = creatorUserTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_groupon.status
     *
     * @return the value of librecmall_groupon.status
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_groupon.status
     *
     * @param status the value for librecmall_groupon.status
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_groupon.add_time
     *
     * @return the value of librecmall_groupon.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_groupon.add_time
     *
     * @param addTime the value for librecmall_groupon.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_groupon.update_time
     *
     * @return the value of librecmall_groupon.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_groupon.update_time
     *
     * @param updateTime the value for librecmall_groupon.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_groupon.deleted
     *
     * @return the value of librecmall_groupon.deleted
     *
     * @mbggenerated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_groupon.deleted
     *
     * @param deleted the value for librecmall_groupon.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}