package pojo;

import java.util.Date;

public class NoticeAdmin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_notice_admin.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_notice_admin.notice_id
     *
     * @mbggenerated
     */
    private Integer noticeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_notice_admin.notice_title
     *
     * @mbggenerated
     */
    private String noticeTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_notice_admin.admin_id
     *
     * @mbggenerated
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_notice_admin.read_time
     *
     * @mbggenerated
     */
    private Date readTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_notice_admin.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_notice_admin.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_notice_admin.deleted
     *
     * @mbggenerated
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_notice_admin.id
     *
     * @return the value of librecmall_notice_admin.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_notice_admin.id
     *
     * @param id the value for librecmall_notice_admin.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_notice_admin.notice_id
     *
     * @return the value of librecmall_notice_admin.notice_id
     *
     * @mbggenerated
     */
    public Integer getNoticeId() {
        return noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_notice_admin.notice_id
     *
     * @param noticeId the value for librecmall_notice_admin.notice_id
     *
     * @mbggenerated
     */
    public void setNoticeId(Integer noticeId) {
        this.noticeId = noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_notice_admin.notice_title
     *
     * @return the value of librecmall_notice_admin.notice_title
     *
     * @mbggenerated
     */
    public String getNoticeTitle() {
        return noticeTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_notice_admin.notice_title
     *
     * @param noticeTitle the value for librecmall_notice_admin.notice_title
     *
     * @mbggenerated
     */
    public void setNoticeTitle(String noticeTitle) {
        this.noticeTitle = noticeTitle == null ? null : noticeTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_notice_admin.admin_id
     *
     * @return the value of librecmall_notice_admin.admin_id
     *
     * @mbggenerated
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_notice_admin.admin_id
     *
     * @param adminId the value for librecmall_notice_admin.admin_id
     *
     * @mbggenerated
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_notice_admin.read_time
     *
     * @return the value of librecmall_notice_admin.read_time
     *
     * @mbggenerated
     */
    public Date getReadTime() {
        return readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_notice_admin.read_time
     *
     * @param readTime the value for librecmall_notice_admin.read_time
     *
     * @mbggenerated
     */
    public void setReadTime(Date readTime) {
        this.readTime = readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_notice_admin.add_time
     *
     * @return the value of librecmall_notice_admin.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_notice_admin.add_time
     *
     * @param addTime the value for librecmall_notice_admin.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_notice_admin.update_time
     *
     * @return the value of librecmall_notice_admin.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_notice_admin.update_time
     *
     * @param updateTime the value for librecmall_notice_admin.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_notice_admin.deleted
     *
     * @return the value of librecmall_notice_admin.deleted
     *
     * @mbggenerated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_notice_admin.deleted
     *
     * @param deleted the value for librecmall_notice_admin.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}