package pojo;

import java.util.Date;

public class System {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_system.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_system.key_name
     *
     * @mbggenerated
     */
    private String keyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_system.key_value
     *
     * @mbggenerated
     */
    private String keyValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_system.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_system.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column librecmall_system.deleted
     *
     * @mbggenerated
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_system.id
     *
     * @return the value of librecmall_system.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_system.id
     *
     * @param id the value for librecmall_system.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_system.key_name
     *
     * @return the value of librecmall_system.key_name
     *
     * @mbggenerated
     */
    public String getKeyName() {
        return keyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_system.key_name
     *
     * @param keyName the value for librecmall_system.key_name
     *
     * @mbggenerated
     */
    public void setKeyName(String keyName) {
        this.keyName = keyName == null ? null : keyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_system.key_value
     *
     * @return the value of librecmall_system.key_value
     *
     * @mbggenerated
     */
    public String getKeyValue() {
        return keyValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_system.key_value
     *
     * @param keyValue the value for librecmall_system.key_value
     *
     * @mbggenerated
     */
    public void setKeyValue(String keyValue) {
        this.keyValue = keyValue == null ? null : keyValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_system.add_time
     *
     * @return the value of librecmall_system.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_system.add_time
     *
     * @param addTime the value for librecmall_system.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_system.update_time
     *
     * @return the value of librecmall_system.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_system.update_time
     *
     * @param updateTime the value for librecmall_system.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column librecmall_system.deleted
     *
     * @return the value of librecmall_system.deleted
     *
     * @mbggenerated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column librecmall_system.deleted
     *
     * @param deleted the value for librecmall_system.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}